param(
    [string]$MathlibRoot = 'C:\Users\cleon\MeusTeoremas\.lake\packages\mathlib',
    [string]$LeanExe = 'C:\Users\cleon\.elan\toolchains\leanprover--lean4---v4.34.0-rc2\bin\lean.exe'
)
$ErrorActionPreference = 'Stop'
$checker = Join-Path $PSScriptRoot 'check-local.ps1'
$modules = @(
    'BFPP/Transfer.lean',
    'BFPP/Suprema.lean',
    'BFPP/BoundedFamilies.lean',
    'BFPP/Envelopes.lean',
    'BFPP/Profiles.lean',
    'BFPP/ProfileGeometry.lean',
    'BFPP/Center.lean',
    'BFPP/TwoProfiles.lean',
    'BFPP/TwoProfileGeometry.lean',
    'BFPP/ContinuousBall.lean',
    'BFPP/FSpaceNecessary.lean',
    'BFPP/Deficits.lean',
    'BFPP/Analysis.lean',
    'BFPP/Regularization.lean',
    'BFPP/C0Profiles.lean',
    'BFPP/FiniteSynthesis.lean',
    'BFPP/StepFunctions.lean',
    'BFPP/StepAlgebra.lean',
    'BFPP/PositiveSynthesis.lean',
    'BFPP/CenteredSynthesis.lean',
    'BFPP/Families.lean',
    'BFPP/Realization.lean',
    'BFPP/OrdinalIndex.lean',
    'BFPP/Cozero.lean',
    'BFPP/SaturatedChains.lean',
    'BFPP/SignExtension.lean',
    'BFPP/Hartogs.lean',
    'BFPP/SignRecursion.lean',
    'BFPP/SignTermination.lean',
    'BFPP/SignRealization.lean',
    'BFPP/ChainCompleteness.lean',
    'BFPP/BooleanGap.lean',
    'BFPP/CofinalSequences.lean',
    'BFPP/IndexedGaps.lean',
    'BFPP/ClopenCompleteness.lean',
    'BFPP/ClopenPairs.lean',
    'BFPP/CofinalReindexing.lean',
    'BFPP/Necessity.lean',
    'BFPP/EDSupremum.lean',
    'BFPP/BallOrderGeometry.lean',
    'BFPP/InvariantIntervals.lean',
    'BFPP/LatticeFixedPoint.lean',
    'BFPP/Characterization.lean',
    'BFPP/OrdinalCofinality.lean',
    'BFPP/CountablePairs.lean',
    'BFPP/RegularPairs.lean',
    'BFPP/OrdinalPairs.lean',
    'BFPP/ProfileExtension.lean',
    'BFPP/ExtensionDelay.lean',
    'BFPP/Interleaving.lean',
    'BFPP/TwoProfileStructure.lean',
    'BFPP/EncodedDomain.lean',
    'BFPP/EnvelopeOrder.lean',
    'BFPP/InterleavingEnvelopes.lean',
    'BFPP/ProfileRestriction.lean',
    'BFPP/EncodedMaps.lean',
    'BFPP/PrefixFactorization.lean',
    'BFPP/TransfinitePropagator.lean',
    'BFPP/DelayPrefixBound.lean',
    'BFPP/EncodedRecurrence.lean',
    'BFPP/MainTransfinite.lean',
    'BFPP/EncodedRules.lean',
    'BFPP/ComplexBall.lean',
    'BFPP/SynthesisMeasure.lean',
    'BFPP/SynthesisIntegral.lean',
    'BFPP/PointwiseSupremum.lean',
    'BFPP/PointwisePrefixes.lean',
    'BFPP/TerminalSupremum.lean',
    'BFPP/TerminalNormalization.lean',
    'BFPP/NormalizedAppendix.lean',
    'BFPP/ConvexIntegral.lean',
    'BFPP/BallScaling.lean',
    'BFPP/DiscretePropagation.lean',
    'BFPP.lean',
    'Audit.lean'
)
foreach ($module in $modules) {
    Write-Output "Checking $module"
    & $checker -File $module -MathlibRoot $MathlibRoot -LeanExe $LeanExe
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
}
Write-Output 'All listed modules and the axiom audit checked successfully.'
